version: "3"
services:
  node:
    image: intama-info-v.1:latest
    container_name: intama-service-keystone
    ports:
      - "3000:3000"
    environment:
      - ESSION_SECRET="ABCDEFGH1234567887654321HGFEDCBA"
      - NODE_ENV=production
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST_APP=intama-service-db
      - KEYSTONE_DB_USER=root
      - KEYSTONE_DB_PASSWORD=root
      - DATABASE_URL=mysql://root:root@intama-service-db:3306/Intama
      - KEYSTONE_DB_NAME=Intama
    networks:
      - docker-service
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.9.2
    container_name: intama-service-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
